import { APP_NAME } from './config.js';
import { select } from './dom.js';
import { setupTheme } from './theme.js';
import { setupSearch } from './search.js';
import { setupWorkspace, loadRoots } from './workspace.js';
import { setupNavigation } from './navigation.js';
import { openDocument } from './rendering.js';
import { setupIcons } from './icons.js';
import { setupOrientation } from './orientation.js';
import { setupContinuity } from './continuity.js';
import { setupReadingTools } from './reading-tools.js';
import { setupReviews } from './reviews.js';
import { setupActions } from './actions.js';
import { recovery } from './recovery.js';
import { setupShell } from './shell.js';
import { setupReadingLayout } from './reading-layout.js';

document.title = APP_NAME;
select('#crumb').textContent = APP_NAME;
setupIcons();
setupTheme();
setupSearch();
setupWorkspace();
setupNavigation();
setupOrientation();
setupReadingTools();
setupContinuity();
setupReviews();
setupActions();
setupShell();
setupReadingLayout();
const start = () => loadRoots().then(openDocument).catch(() => recovery(select('#doc'), 'Workspace unavailable or server unreachable.', start));
start();
